[package]
name = "leki"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-secrets = "0.34.0"
shuttle-serenity = "0.34.0"
shuttle-runtime = "0.34.0"
anyhow = "1.0.75"
thiserror = "1.0.50"
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "builder"] }
tokio = "1.34.0"
tracing = "0.1.40"
chrono = "0.4.31"
duration-string="0.3"
log = "0.4.20"
regex = "1.10"
lazy_static = "1"
