[package]
name = "leki"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-shared-db = { version = "0.30.1", features = ["postgres"] }
shuttle-secrets = "0.30.1"
shuttle-serenity = "0.30.1"
shuttle-runtime = "0.30.1"
anyhow = "1.0.75"
thiserror = "1.0.50"
fang = { version = "0.10.4"}
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "builder"] }
tokio = "1.33.0"
tracing = "0.1.40"
chrono = "0.4.31"
duration-string="0.3"
log = "0.4.20"
regex = "1"
lazy_static = "1"
sqlx = { version = "0.7.2", features = ["macros"] }
