name: Restart

on: workflow_dispatch

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Install Shuttle CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-shuttle

      - name: Authenticate API Key
        run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}

      - name: Restart bot
        run: cargo shuttle project restart --idle-minutes 0 --name leki
